# Generated by Django 3.2.5 on 2021-07-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0006_auto_20210728_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Телеграмм'),
        ),
    ]
