# Generated by Django 3.2.5 on 2021-07-30 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LK', '0007_alter_profile_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lkpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_page', models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Изображение')),
                ('text_page', models.TextField(verbose_name='Статья')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
