# Generated by Django 3.2.5 on 2021-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0008_lkpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpage',
            name='preview_page',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='lkpage',
            name='title_page',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
