# Generated by Django 3.2.5 on 2021-08-06 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0014_alter_lkpage_data_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpage',
            name='data_page',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 6, 22, 38, 330679), verbose_name='Дата'),
        ),
    ]
