# Generated by Django 3.2.5 on 2021-08-08 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0016_alter_lkpage_data_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpage',
            name='data_page',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 7, 43, 1, 401286), verbose_name='Дата'),
        ),
    ]
