# Generated by Django 3.2.5 on 2021-08-18 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0020_alter_lkpage_data_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpage',
            name='data_page',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 18, 9, 23, 44, 555286), null=True, verbose_name='Дата'),
        ),
    ]
