# Generated by Django 3.2.5 on 2021-08-18 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0026_auto_20210818_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkpage',
            name='created_page',
        ),
        migrations.RemoveField(
            model_name='lkpage',
            name='updated_page',
        ),
        migrations.AddField(
            model_name='lkpage',
            name='data_page',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 17, 7, 51, 422329), verbose_name='Дата'),
        ),
    ]
