# Generated by Django 3.2.5 on 2021-08-22 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0027_auto_20210818_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkpage',
            old_name='user',
            new_name='author_page',
        ),
        migrations.AlterField(
            model_name='lkpage',
            name='data_page',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 11, 19, 30, 79284, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
