# Generated by Django 3.2.5 on 2021-08-22 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0028_auto_20210822_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkpage',
            old_name='author_page',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='lkpage',
            name='data_page',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 12, 24, 48, 993091, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
