# Generated by Django 3.2.5 on 2021-08-25 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0030_auto_20210823_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpage',
            name='data_page',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 6, 39, 38, 472176, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='lkpage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lkpages', to='LK.Tag'),
        ),
    ]
