# Generated by Django 3.2.5 on 2021-07-19 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelsnewspage',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='modelsnewspage',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 1, 2, 2, 736635), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='modelsnewspage',
            name='preview',
            field=models.CharField(default='', max_length=300, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='modelsnewspage',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
    ]
