# Generated by Django 3.2.5 on 2021-07-19 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210720_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsnewspage',
            name='img',
            field=models.ImageField(default=None, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='modelsnewspage',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 1, 20, 35, 220111), verbose_name='Дата'),
        ),
    ]
