# Generated by Django 3.2.5 on 2021-07-19 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210720_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsnewspage',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 1, 24, 58, 313560), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='modelsnewspage',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
