# Generated by Django 3.2.5 on 2021-08-17 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_modelsnewspage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsnewspage',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 13, 23, 32, 27866), verbose_name='Дата'),
        ),
    ]
