# Generated by Django 3.2.5 on 2021-08-22 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_modelsnewspage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsnewspage',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 15, 24, 48, 996101), verbose_name='Дата'),
        ),
    ]
