# Generated by Django 3.2.5 on 2021-08-25 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_modelsnewspage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsnewspage',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 9, 39, 38, 475177), verbose_name='Дата'),
        ),
    ]
