# Generated by Django 3.2.5 on 2021-08-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_comment',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания комментария'),
        ),
    ]
