# Generated by Django 3.2.5 on 2021-08-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_rename_user_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img_сom',
        ),
    ]
