# Generated by Django 3.2.5 on 2021-08-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_remove_comment_img_сom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
